# Server
source:          docs
destination:     docs/_site
host:            0.0.0.0
port:            5000
baseurl:

# Assets
assets:
  dirname:       _assets
  baseurl:       /_assets/
  sources:
    - ../src/javascripts
    - ../src/stylesheets
    - ../src/images
    - ../src/fonts
  js_compressor:  ~
  css_compressor: none
  # cachebust:      none
  # cache:          true
  gzip:           [ text/css, application/javascript ]
  version:        1
  debug:          true

# Custom Variables
title:            Cascade Assets